import { MarketplaceKit } from '../types/generator';

// Pre-generated local image assets
import plannerKitImg from '../assets/images/marketplace_planner_kit_1790748618449.jpg';
import creatorTemplatesImg from '../assets/images/marketplace_creator_templates_1790748631935.jpg';
import brandKitImg from '../assets/images/marketplace_brand_kit_1790748647435.jpg';

export const BOOK_KAARO_MARKETPLACE_KITS: MarketplaceKit[] = [
  {
    id: 'bk-planner-90day',
    title: 'Book Kaaro 90-Day Social Content Journal',
    subtitle: 'Structured Notion & Printable Planner for Consistent Posting',
    category: 'Content Planners',
    format: 'Notion Template + Printable PDF',
    description:
      'A structured editorial workspace built to map quarterly themes, track weekly output across 4 channels, and archive top-performing hooks. Clearly labeled as a Book Kaaro Digital Template preview.',
    imageUrl: plannerKitImg,
    badge: 'Official Template Preview',
    priceLabel: 'Included in Book Kaaro Pro / Free Community Edition',
    includes: [
      'Multi-channel weekly calendar database (Instagram, FB, LinkedIn, TikTok)',
      'Hook archive vault with categorization tags',
      'Hashtag group manager & character limit check sheets',
      'Monthly audit review matrix with qualitative notes'
    ],
    compatiblePlatforms: ['instagram', 'facebook', 'linkedin', 'tiktok'],
    previewOverview:
      'Designed to sync directly with the weekly calendar generated above. Import your 7-day plan directly into the Notion database or print the A4 weekly grid for desk planning.'
  },
  {
    id: 'bk-creator-templates',
    title: 'Book Kaaro Multi-Platform Carousel & Post Templates',
    subtitle: '50+ Clean Editorial Figma & Canva Layouts',
    category: 'Social Media Templates',
    format: 'Canva Pro & Figma Kit',
    description:
      'Cohesive, typographic slide decks and feed grids designed for high legibility without cluttered pills or AI slop. Built specifically for educational carousels, case breakdowns, and quote graphics.',
    imageUrl: creatorTemplatesImg,
    badge: 'Design System Preview',
    priceLabel: 'Curated Resource Placeholder',
    includes: [
      '20 Seamless Carousel slides (1080x1350 Instagram/LinkedIn portrait)',
      '15 Short-form video text overlay title cards (1080x1920 9:16)',
      '10 B2B quote and data card layouts',
      'Curated font pairing guide using accessible Google Fonts'
    ],
    compatiblePlatforms: ['instagram', 'linkedin', 'facebook'],
    previewOverview:
      'Direct visual pairing for the Short and Long captions generated by this tool. Simply paste the hook into Slide 1 and the breakdown into Slides 2-5.'
  },
  {
    id: 'bk-brand-marketing-kit',
    title: 'Book Kaaro Organic Social Conversion Blueprint',
    subtitle: 'Strategic Messaging Framework & Call-to-Action Library',
    category: 'Marketing Kits',
    format: 'Guidebook + Copy Swipe File (PDF + Docs)',
    description:
      'A practical messaging system that helps small businesses, service providers, and creators communicate value clearly without hype, ungrounded statistics, or aggressive sales tactics.',
    imageUrl: brandKitImg,
    badge: 'Resource Guide Placeholder',
    priceLabel: 'Open Strategy Guide',
    includes: [
      '75 Tested call-to-action formulas categorized by customer journey stage',
      'Tone-of-voice alignment worksheet for teams and solo founders',
      'B2B thought leadership structuring templates',
      'Ethical social marketing checklist (no fake testimonials or inflated claims)'
    ],
    compatiblePlatforms: ['linkedin', 'instagram', 'facebook', 'tiktok'],
    previewOverview:
      'Enhance your generated hooks and CTAs with deep contextual positioning frameworks tailored for honest, value-driven community growth.'
  }
];
